language: python
python:
  - "3.4"
    # command to install dependencies
sudo: false
cache: pip
addons:
  apt:
    packages:
      - python-qt4
      - python-qt4-dev
      - pyqt4-dev-tools
# load system_site_packages into virtualenv to make PyQt4 available
virtualenv:
  system_site_packages: true
before_install:
  - pip install codecov
after_success:
  - codecov
# command to run tests
script:
  - cd FabLabKasse/UI/ && ./compile_all.py
  - cd ../../ && coverage run run_unittests.py
