# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/patrick/Dokumente/FabLab/Kassenterminal/FabLabKasse/FabLabKasse/UI/Kassenterminal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kassenterminal(object):
    def setupUi(self, Kassenterminal):
        Kassenterminal.setObjectName("Kassenterminal")
        Kassenterminal.resize(1280, 1018)
        font = QtGui.QFont()
        font.setFamily("Carlito")
        font.setPointSize(14)
        Kassenterminal.setFont(font)
        Kassenterminal.setIconSize(QtCore.QSize(10, 10))
        Kassenterminal.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Kassenterminal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_category_path = QtWidgets.QWidget(self.centralwidget)
        self.widget_category_path.setStyleSheet("*{\n"
"padding:0px;\n"
"margin:0px;\n"
"}\n"
"QPushButton{\n"
"padding:5px;\n"
"margin:0px;\n"
"font-size:14pt;\n"
"/* blue color:\n"
" background-color: rgb(44, 114, 199);\n"
"color: white;  */\n"
"}\n"
"#pushButton_start{\n"
"font-size: 16pt;\n"
"}")
        self.widget_category_path.setObjectName("widget_category_path")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_category_path)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_category_path)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_13.addWidget(self.pushButton_start)
        self.layout_category_path = QtWidgets.QHBoxLayout()
        self.layout_category_path.setObjectName("layout_category_path")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_category_path)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.layout_category_path.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_category_path)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.layout_category_path.addWidget(self.pushButton_17)
        self.label_2 = QtWidgets.QLabel(self.widget_category_path)
        self.label_2.setObjectName("label_2")
        self.layout_category_path.addWidget(self.label_2)
        self.horizontalLayout_13.addLayout(self.layout_category_path)
        self.horizontalLayout_5.addWidget(self.widget_category_path)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_load_cart_from_app = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_cart_from_app.sizePolicy().hasHeightForWidth())
        self.pushButton_load_cart_from_app.setSizePolicy(sizePolicy)
        self.pushButton_load_cart_from_app.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_load_cart_from_app.setObjectName("pushButton_load_cart_from_app")
        self.horizontalLayout_5.addWidget(self.pushButton_load_cart_from_app)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.lineEdit_Suche = MyQLineEdit(self.centralwidget)
        self.lineEdit_Suche.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Suche.sizePolicy().hasHeightForWidth())
        self.lineEdit_Suche.setSizePolicy(sizePolicy)
        self.lineEdit_Suche.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_Suche.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_Suche.setFont(font)
        self.lineEdit_Suche.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_Suche.setAutoFillBackground(False)
        self.lineEdit_Suche.setText("")
        self.lineEdit_Suche.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Suche.setDragEnabled(False)
        self.lineEdit_Suche.setObjectName("lineEdit_Suche")
        self.horizontalLayout_5.addWidget(self.lineEdit_Suche, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_kategorien = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_kategorien.setFont(font)
        self.label_kategorien.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kategorien.setObjectName("label_kategorien")
        self.verticalLayout_9.addWidget(self.label_kategorien)
        self.list_categories = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_categories.sizePolicy().hasHeightForWidth())
        self.list_categories.setSizePolicy(sizePolicy)
        self.list_categories.setMinimumSize(QtCore.QSize(270, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_categories.setFont(font)
        self.list_categories.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_categories.setStyleSheet("QScrollBar:vertical {\n"
"    width: 40px;\n"
"}")
        self.list_categories.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list_categories.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_categories.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_categories.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.list_categories.setObjectName("list_categories")
        self.verticalLayout_9.addWidget(self.list_categories)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.table_products = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_products.setFont(font)
        self.table_products.setFocusPolicy(QtCore.Qt.NoFocus)
        self.table_products.setStyleSheet("QScrollBar:vertical {\n"
"    width: 40px;\n"
"}")
        self.table_products.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_products.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_products.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_products.setAlternatingRowColors(True)
        self.table_products.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_products.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_products.setObjectName("table_products")
        self.table_products.horizontalHeader().setDefaultSectionSize(250)
        self.table_products.horizontalHeader().setStretchLastSection(True)
        self.table_products.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.table_products)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_basket = QtWidgets.QWidget()
        self.page_basket.setEnabled(True)
        self.page_basket.setObjectName("page_basket")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_basket)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabOrders = QtWidgets.QTabWidget(self.page_basket)
        self.tabOrders.setDocumentMode(True)
        self.tabOrders.setObjectName("tabOrders")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.table_order = CartTableView(self.tab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.table_order.setFont(font)
        self.table_order.setFocusPolicy(QtCore.Qt.NoFocus)
        self.table_order.setStyleSheet("QScrollBar:vertical {\n"
"    width: 40px;\n"
"}")
        self.table_order.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_order.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_order.setAlternatingRowColors(True)
        self.table_order.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_order.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_order.setObjectName("table_order")
        self.table_order.horizontalHeader().setHighlightSections(True)
        self.horizontalLayout_11.addWidget(self.table_order)
        self.tabOrders.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabOrders)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSumme = QtWidgets.QLabel(self.page_basket)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.labelSumme.setFont(font)
        self.labelSumme.setObjectName("labelSumme")
        self.horizontalLayout_2.addWidget(self.labelSumme)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.summe = QtWidgets.QLabel(self.page_basket)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.summe.setFont(font)
        self.summe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.summe.setObjectName("summe")
        self.horizontalLayout_2.addWidget(self.summe)
        self.pushButton_clearCart = QtWidgets.QPushButton(self.page_basket)
        self.pushButton_clearCart.setEnabled(False)
        self.pushButton_clearCart.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clearCart.setFont(font)
        self.pushButton_clearCart.setFlat(False)
        self.pushButton_clearCart.setObjectName("pushButton_clearCart")
        self.horizontalLayout_2.addWidget(self.pushButton_clearCart)
        self.pushButton_payup = QtWidgets.QPushButton(self.page_basket)
        self.pushButton_payup.setEnabled(False)
        self.pushButton_payup.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_payup.setFont(font)
        self.pushButton_payup.setFlat(False)
        self.pushButton_payup.setObjectName("pushButton_payup")
        self.horizontalLayout_2.addWidget(self.pushButton_payup)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_unit = QtWidgets.QLabel(self.page_basket)
        self.label_unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_unit.setObjectName("label_unit")
        self.horizontalLayout_3.addWidget(self.label_unit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.lineEdit = QtWidgets.QLineEdit(self.page_basket)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_OK = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_OK.sizePolicy().hasHeightForWidth())
        self.pushButton_OK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("action-okay")
        self.pushButton_OK.setIcon(icon)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout.addWidget(self.pushButton_OK, 3, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_backspace = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_backspace.sizePolicy().hasHeightForWidth())
        self.pushButton_backspace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_backspace.setFont(font)
        self.pushButton_backspace.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_backspace.setObjectName("pushButton_backspace")
        self.gridLayout.addWidget(self.pushButton_backspace, 0, 3, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete.sizePolicy().hasHeightForWidth())
        self.pushButton_delete.setSizePolicy(sizePolicy)
        self.pushButton_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_delete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/trashcan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon)
        self.pushButton_delete.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 3, 1, 1)
        self.pushButton_decimal_point = QtWidgets.QPushButton(self.page_basket)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_decimal_point.sizePolicy().hasHeightForWidth())
        self.pushButton_decimal_point.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_decimal_point.setFont(font)
        self.pushButton_decimal_point.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_decimal_point.setObjectName("pushButton_decimal_point")
        self.gridLayout.addWidget(self.pushButton_decimal_point, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page_basket)
        self.page_keyboard = QtWidgets.QWidget()
        self.page_keyboard.setObjectName("page_keyboard")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_keyboard)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_n = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_n.sizePolicy().hasHeightForWidth())
        self.pushButton_n.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n.setFont(font)
        self.pushButton_n.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_n.setObjectName("pushButton_n")
        self.gridLayout_3.addWidget(self.pushButton_n, 3, 6, 1, 1)
        self.pushButton_m = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_m.sizePolicy().hasHeightForWidth())
        self.pushButton_m.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_m.setFont(font)
        self.pushButton_m.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_m.setObjectName("pushButton_m")
        self.gridLayout_3.addWidget(self.pushButton_m, 3, 7, 1, 1)
        self.pushButton_j = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j.sizePolicy().hasHeightForWidth())
        self.pushButton_j.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_j.setFont(font)
        self.pushButton_j.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_j.setObjectName("pushButton_j")
        self.gridLayout_3.addWidget(self.pushButton_j, 2, 6, 1, 1)
        self.pushButton_s = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_s.sizePolicy().hasHeightForWidth())
        self.pushButton_s.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_s.setFont(font)
        self.pushButton_s.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_s.setObjectName("pushButton_s")
        self.gridLayout_3.addWidget(self.pushButton_s, 2, 1, 1, 1)
        self.pushButton_o = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_o.sizePolicy().hasHeightForWidth())
        self.pushButton_o.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_o.setFont(font)
        self.pushButton_o.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_o.setObjectName("pushButton_o")
        self.gridLayout_3.addWidget(self.pushButton_o, 1, 8, 1, 1)
        self.pushButton_q = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_q.sizePolicy().hasHeightForWidth())
        self.pushButton_q.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_q.setFont(font)
        self.pushButton_q.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_q.setObjectName("pushButton_q")
        self.gridLayout_3.addWidget(self.pushButton_q, 1, 0, 1, 1)
        self.pushButton_i = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_i.sizePolicy().hasHeightForWidth())
        self.pushButton_i.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_i.setFont(font)
        self.pushButton_i.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_i.setObjectName("pushButton_i")
        self.gridLayout_3.addWidget(self.pushButton_i, 1, 7, 1, 1)
        self.pushButton_w = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_w.sizePolicy().hasHeightForWidth())
        self.pushButton_w.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_w.setFont(font)
        self.pushButton_w.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_w.setObjectName("pushButton_w")
        self.gridLayout_3.addWidget(self.pushButton_w, 1, 1, 1, 1)
        self.pushButton_u = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_u.sizePolicy().hasHeightForWidth())
        self.pushButton_u.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_u.setFont(font)
        self.pushButton_u.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_u.setObjectName("pushButton_u")
        self.gridLayout_3.addWidget(self.pushButton_u, 1, 6, 1, 1)
        self.pushButton_d = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_d.sizePolicy().hasHeightForWidth())
        self.pushButton_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_d.setFont(font)
        self.pushButton_d.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_d.setObjectName("pushButton_d")
        self.gridLayout_3.addWidget(self.pushButton_d, 2, 2, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout_3.addWidget(self.pushButton_dot, 3, 9, 1, 1)
        self.pushButton_komma = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_komma.sizePolicy().hasHeightForWidth())
        self.pushButton_komma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_komma.setFont(font)
        self.pushButton_komma.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_komma.setObjectName("pushButton_komma")
        self.gridLayout_3.addWidget(self.pushButton_komma, 3, 8, 1, 1)
        self.pushButton_space = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_space.sizePolicy().hasHeightForWidth())
        self.pushButton_space.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_space.setFont(font)
        self.pushButton_space.setText("")
        self.pushButton_space.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_space.setObjectName("pushButton_space")
        self.gridLayout_3.addWidget(self.pushButton_space, 4, 2, 1, 6)
        self.pushButton_enter = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enter.sizePolicy().hasHeightForWidth())
        self.pushButton_enter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.gridLayout_3.addWidget(self.pushButton_enter, 2, 11, 2, 1)
        self.pushButton_a_4 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_4.sizePolicy().hasHeightForWidth())
        self.pushButton_a_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_4.setFont(font)
        self.pushButton_a_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_4.setObjectName("pushButton_a_4")
        self.gridLayout_3.addWidget(self.pushButton_a_4, 0, 4, 1, 1)
        self.pushButton_a_6 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_6.sizePolicy().hasHeightForWidth())
        self.pushButton_a_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_6.setFont(font)
        self.pushButton_a_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_6.setObjectName("pushButton_a_6")
        self.gridLayout_3.addWidget(self.pushButton_a_6, 0, 6, 1, 1)
        self.pushButton_v = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_v.sizePolicy().hasHeightForWidth())
        self.pushButton_v.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_v.setFont(font)
        self.pushButton_v.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_v.setObjectName("pushButton_v")
        self.gridLayout_3.addWidget(self.pushButton_v, 3, 4, 1, 1)
        self.pushButton_p = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_p.sizePolicy().hasHeightForWidth())
        self.pushButton_p.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_p.setFont(font)
        self.pushButton_p.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_p.setObjectName("pushButton_p")
        self.gridLayout_3.addWidget(self.pushButton_p, 1, 9, 1, 1)
        self.pushButton_b = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_b.sizePolicy().hasHeightForWidth())
        self.pushButton_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_b.setFont(font)
        self.pushButton_b.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_b.setObjectName("pushButton_b")
        self.gridLayout_3.addWidget(self.pushButton_b, 3, 5, 1, 1)
        self.pushButton_k = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_k.sizePolicy().hasHeightForWidth())
        self.pushButton_k.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_k.setFont(font)
        self.pushButton_k.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_k.setObjectName("pushButton_k")
        self.gridLayout_3.addWidget(self.pushButton_k, 2, 7, 1, 1)
        self.pushButton_backspace_3 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_backspace_3.sizePolicy().hasHeightForWidth())
        self.pushButton_backspace_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_backspace_3.setFont(font)
        self.pushButton_backspace_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_backspace_3.setObjectName("pushButton_backspace_3")
        self.gridLayout_3.addWidget(self.pushButton_backspace_3, 1, 11, 1, 1)
        self.pushButton_e = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_e.sizePolicy().hasHeightForWidth())
        self.pushButton_e.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_e.setFont(font)
        self.pushButton_e.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_e.setObjectName("pushButton_e")
        self.gridLayout_3.addWidget(self.pushButton_e, 1, 2, 1, 1)
        self.pushButton_x = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_x.sizePolicy().hasHeightForWidth())
        self.pushButton_x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_x.setFont(font)
        self.pushButton_x.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_x.setObjectName("pushButton_x")
        self.gridLayout_3.addWidget(self.pushButton_x, 3, 2, 1, 1)
        self.pushButton_c = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_c.sizePolicy().hasHeightForWidth())
        self.pushButton_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c.setFont(font)
        self.pushButton_c.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_c.setObjectName("pushButton_c")
        self.gridLayout_3.addWidget(self.pushButton_c, 3, 3, 1, 1)
        self.pushButton_ae = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ae.sizePolicy().hasHeightForWidth())
        self.pushButton_ae.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ae.setFont(font)
        self.pushButton_ae.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_ae.setObjectName("pushButton_ae")
        self.gridLayout_3.addWidget(self.pushButton_ae, 2, 10, 1, 1)
        self.pushButton_a_1 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_1.sizePolicy().hasHeightForWidth())
        self.pushButton_a_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_1.setFont(font)
        self.pushButton_a_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_1.setObjectName("pushButton_a_1")
        self.gridLayout_3.addWidget(self.pushButton_a_1, 0, 1, 1, 1)
        self.pushButton_a = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a.sizePolicy().hasHeightForWidth())
        self.pushButton_a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a.setFont(font)
        self.pushButton_a.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a.setObjectName("pushButton_a")
        self.gridLayout_3.addWidget(self.pushButton_a, 2, 0, 1, 1)
        self.pushButton_t = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_t.sizePolicy().hasHeightForWidth())
        self.pushButton_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_t.setFont(font)
        self.pushButton_t.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_t.setObjectName("pushButton_t")
        self.gridLayout_3.addWidget(self.pushButton_t, 1, 4, 1, 1)
        self.pushButton_z = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_z.sizePolicy().hasHeightForWidth())
        self.pushButton_z.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_z.setFont(font)
        self.pushButton_z.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_z.setObjectName("pushButton_z")
        self.gridLayout_3.addWidget(self.pushButton_z, 1, 5, 1, 1)
        self.pushButton_a_3 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_3.sizePolicy().hasHeightForWidth())
        self.pushButton_a_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_3.setFont(font)
        self.pushButton_a_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_3.setObjectName("pushButton_a_3")
        self.gridLayout_3.addWidget(self.pushButton_a_3, 0, 3, 1, 1)
        self.pushButton_l = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_l.sizePolicy().hasHeightForWidth())
        self.pushButton_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_l.setFont(font)
        self.pushButton_l.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_l.setObjectName("pushButton_l")
        self.gridLayout_3.addWidget(self.pushButton_l, 2, 8, 1, 1)
        self.pushButton_a_2 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_2.sizePolicy().hasHeightForWidth())
        self.pushButton_a_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_2.setFont(font)
        self.pushButton_a_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_2.setObjectName("pushButton_a_2")
        self.gridLayout_3.addWidget(self.pushButton_a_2, 0, 2, 1, 1)
        self.pushButton_r = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_r.sizePolicy().hasHeightForWidth())
        self.pushButton_r.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_r.setFont(font)
        self.pushButton_r.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_r.setObjectName("pushButton_r")
        self.gridLayout_3.addWidget(self.pushButton_r, 1, 3, 1, 1)
        self.pushButton_a_9 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_9.sizePolicy().hasHeightForWidth())
        self.pushButton_a_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_9.setFont(font)
        self.pushButton_a_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_9.setObjectName("pushButton_a_9")
        self.gridLayout_3.addWidget(self.pushButton_a_9, 0, 9, 1, 1)
        self.pushButton_g = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_g.sizePolicy().hasHeightForWidth())
        self.pushButton_g.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_g.setFont(font)
        self.pushButton_g.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_g.setObjectName("pushButton_g")
        self.gridLayout_3.addWidget(self.pushButton_g, 2, 4, 1, 1)
        self.pushButton_ue = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ue.sizePolicy().hasHeightForWidth())
        self.pushButton_ue.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ue.setFont(font)
        self.pushButton_ue.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_ue.setObjectName("pushButton_ue")
        self.gridLayout_3.addWidget(self.pushButton_ue, 1, 10, 1, 1)
        self.pushButton_f = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_f.sizePolicy().hasHeightForWidth())
        self.pushButton_f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_f.setFont(font)
        self.pushButton_f.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_f.setObjectName("pushButton_f")
        self.gridLayout_3.addWidget(self.pushButton_f, 2, 3, 1, 1)
        self.pushButton_oe = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_oe.sizePolicy().hasHeightForWidth())
        self.pushButton_oe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_oe.setFont(font)
        self.pushButton_oe.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_oe.setObjectName("pushButton_oe")
        self.gridLayout_3.addWidget(self.pushButton_oe, 2, 9, 1, 1)
        self.pushButton_h = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_h.sizePolicy().hasHeightForWidth())
        self.pushButton_h.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_h.setFont(font)
        self.pushButton_h.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_h.setObjectName("pushButton_h")
        self.gridLayout_3.addWidget(self.pushButton_h, 2, 5, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.gridLayout_3.addWidget(self.pushButton_minus, 3, 10, 1, 1)
        self.pushButton_y = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_y.sizePolicy().hasHeightForWidth())
        self.pushButton_y.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_y.setFont(font)
        self.pushButton_y.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_y.setObjectName("pushButton_y")
        self.gridLayout_3.addWidget(self.pushButton_y, 3, 1, 1, 1)
        self.pushButton_a_7 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_7.sizePolicy().hasHeightForWidth())
        self.pushButton_a_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_7.setFont(font)
        self.pushButton_a_7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_7.setObjectName("pushButton_a_7")
        self.gridLayout_3.addWidget(self.pushButton_a_7, 0, 7, 1, 1)
        self.pushButton_a_8 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_8.sizePolicy().hasHeightForWidth())
        self.pushButton_a_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_8.setFont(font)
        self.pushButton_a_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_8.setObjectName("pushButton_a_8")
        self.gridLayout_3.addWidget(self.pushButton_a_8, 0, 8, 1, 1)
        self.pushButton_a_5 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_5.sizePolicy().hasHeightForWidth())
        self.pushButton_a_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_5.setFont(font)
        self.pushButton_a_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_5.setObjectName("pushButton_a_5")
        self.gridLayout_3.addWidget(self.pushButton_a_5, 0, 5, 1, 1)
        self.pushButton_a_0 = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_a_0.sizePolicy().hasHeightForWidth())
        self.pushButton_a_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a_0.setFont(font)
        self.pushButton_a_0.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_a_0.setObjectName("pushButton_a_0")
        self.gridLayout_3.addWidget(self.pushButton_a_0, 0, 10, 1, 1)
        self.pushButton_sz = QtWidgets.QPushButton(self.page_keyboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sz.sizePolicy().hasHeightForWidth())
        self.pushButton_sz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sz.setFont(font)
        self.pushButton_sz.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_sz.setObjectName("pushButton_sz")
        self.gridLayout_3.addWidget(self.pushButton_sz, 0, 11, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.page_keyboard)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout_8.setStretch(0, 3)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        Kassenterminal.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Kassenterminal)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        Kassenterminal.setMenuBar(self.menuBar)
        self.actionNeustart = QtWidgets.QAction(Kassenterminal)
        self.actionNeustart.setObjectName("actionNeustart")
        self.actionServicemodus = QtWidgets.QAction(Kassenterminal)
        self.actionServicemodus.setObjectName("actionServicemodus")
        self.menuDatei.addAction(self.actionNeustart)
        self.menuDatei.addAction(self.actionServicemodus)
        self.menuBar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(Kassenterminal)
        self.stackedWidget.setCurrentIndex(0)
        self.tabOrders.setCurrentIndex(0)
        self.actionNeustart.triggered.connect(Kassenterminal.restart)
        self.actionServicemodus.triggered.connect(Kassenterminal.serviceMode)
        QtCore.QMetaObject.connectSlotsByName(Kassenterminal)
        Kassenterminal.setTabOrder(self.lineEdit, self.lineEdit_Suche)
        Kassenterminal.setTabOrder(self.lineEdit_Suche, self.pushButton_payup)
        Kassenterminal.setTabOrder(self.pushButton_payup, self.pushButton_n)
        Kassenterminal.setTabOrder(self.pushButton_n, self.pushButton_m)
        Kassenterminal.setTabOrder(self.pushButton_m, self.pushButton_j)
        Kassenterminal.setTabOrder(self.pushButton_j, self.pushButton_s)
        Kassenterminal.setTabOrder(self.pushButton_s, self.pushButton_o)
        Kassenterminal.setTabOrder(self.pushButton_o, self.pushButton_q)
        Kassenterminal.setTabOrder(self.pushButton_q, self.pushButton_i)
        Kassenterminal.setTabOrder(self.pushButton_i, self.pushButton_w)
        Kassenterminal.setTabOrder(self.pushButton_w, self.pushButton_u)
        Kassenterminal.setTabOrder(self.pushButton_u, self.pushButton_d)
        Kassenterminal.setTabOrder(self.pushButton_d, self.pushButton_dot)
        Kassenterminal.setTabOrder(self.pushButton_dot, self.pushButton_komma)
        Kassenterminal.setTabOrder(self.pushButton_komma, self.pushButton_space)
        Kassenterminal.setTabOrder(self.pushButton_space, self.pushButton_enter)
        Kassenterminal.setTabOrder(self.pushButton_enter, self.pushButton_a_4)
        Kassenterminal.setTabOrder(self.pushButton_a_4, self.pushButton_a_6)
        Kassenterminal.setTabOrder(self.pushButton_a_6, self.pushButton_v)
        Kassenterminal.setTabOrder(self.pushButton_v, self.pushButton_p)
        Kassenterminal.setTabOrder(self.pushButton_p, self.pushButton_b)
        Kassenterminal.setTabOrder(self.pushButton_b, self.pushButton_k)
        Kassenterminal.setTabOrder(self.pushButton_k, self.pushButton_backspace_3)
        Kassenterminal.setTabOrder(self.pushButton_backspace_3, self.pushButton_e)
        Kassenterminal.setTabOrder(self.pushButton_e, self.pushButton_x)
        Kassenterminal.setTabOrder(self.pushButton_x, self.pushButton_c)
        Kassenterminal.setTabOrder(self.pushButton_c, self.pushButton_ae)
        Kassenterminal.setTabOrder(self.pushButton_ae, self.pushButton_a_1)
        Kassenterminal.setTabOrder(self.pushButton_a_1, self.pushButton_a)
        Kassenterminal.setTabOrder(self.pushButton_a, self.pushButton_t)
        Kassenterminal.setTabOrder(self.pushButton_t, self.pushButton_z)
        Kassenterminal.setTabOrder(self.pushButton_z, self.pushButton_a_3)
        Kassenterminal.setTabOrder(self.pushButton_a_3, self.pushButton_l)
        Kassenterminal.setTabOrder(self.pushButton_l, self.pushButton_a_2)
        Kassenterminal.setTabOrder(self.pushButton_a_2, self.pushButton_r)
        Kassenterminal.setTabOrder(self.pushButton_r, self.pushButton_a_9)
        Kassenterminal.setTabOrder(self.pushButton_a_9, self.pushButton_g)
        Kassenterminal.setTabOrder(self.pushButton_g, self.pushButton_ue)
        Kassenterminal.setTabOrder(self.pushButton_ue, self.pushButton_f)
        Kassenterminal.setTabOrder(self.pushButton_f, self.pushButton_oe)
        Kassenterminal.setTabOrder(self.pushButton_oe, self.pushButton_h)
        Kassenterminal.setTabOrder(self.pushButton_h, self.pushButton_minus)
        Kassenterminal.setTabOrder(self.pushButton_minus, self.pushButton_y)
        Kassenterminal.setTabOrder(self.pushButton_y, self.pushButton_a_7)
        Kassenterminal.setTabOrder(self.pushButton_a_7, self.pushButton_a_8)
        Kassenterminal.setTabOrder(self.pushButton_a_8, self.pushButton_a_5)
        Kassenterminal.setTabOrder(self.pushButton_a_5, self.pushButton_a_0)
        Kassenterminal.setTabOrder(self.pushButton_a_0, self.pushButton_sz)

    def retranslateUi(self, Kassenterminal):
        _translate = QtCore.QCoreApplication.translate
        Kassenterminal.setWindowTitle(_translate("Kassenterminal", "FabLab Kassenterminal"))
        self.pushButton_start.setText(_translate("Kassenterminal", "Alle Produkte"))
        self.pushButton_16.setText(_translate("Kassenterminal", "PushButton"))
        self.pushButton_17.setText(_translate("Kassenterminal", "PushButton"))
        self.label_2.setText(_translate("Kassenterminal", "<html><head/><body><p><span style=\" font-size:8pt;\">note: pushButtons inherit style</span></p><p><span style=\" font-size:8pt;\">from widget_category_path</span></p></body></html>"))
        self.pushButton_load_cart_from_app.setText(_translate("Kassenterminal", "Warenkorb\n"
"aus App laden"))
        self.lineEdit_Suche.setPlaceholderText(_translate("Kassenterminal", "Suche..."))
        self.label_kategorien.setText(_translate("Kassenterminal", "Kategorien"))
        self.tabOrders.setTabText(self.tabOrders.indexOf(self.tab), _translate("Kassenterminal", "Warenkorb"))
        self.labelSumme.setText(_translate("Kassenterminal", "Summe:"))
        self.summe.setText(_translate("Kassenterminal", "0,00 €"))
        self.pushButton_clearCart.setText(_translate("Kassenterminal", "Warenkorb leeren"))
        self.pushButton_payup.setText(_translate("Kassenterminal", "Jetzt bezahlen"))
        self.label_unit.setText(_translate("Kassenterminal", "PLU / Artikelnummer:"))
        self.pushButton_5.setText(_translate("Kassenterminal", "5"))
        self.pushButton_OK.setText(_translate("Kassenterminal", "OK"))
        self.pushButton_3.setText(_translate("Kassenterminal", "3"))
        self.pushButton_7.setText(_translate("Kassenterminal", "7"))
        self.pushButton_backspace.setText(_translate("Kassenterminal", "⌫"))
        self.pushButton_1.setText(_translate("Kassenterminal", "1"))
        self.pushButton_9.setText(_translate("Kassenterminal", "9"))
        self.pushButton_2.setText(_translate("Kassenterminal", "2"))
        self.pushButton_0.setText(_translate("Kassenterminal", "0"))
        self.pushButton_6.setText(_translate("Kassenterminal", "6"))
        self.pushButton_8.setText(_translate("Kassenterminal", "8"))
        self.pushButton_4.setText(_translate("Kassenterminal", "4"))
        self.pushButton_decimal_point.setText(_translate("Kassenterminal", ","))
        self.pushButton_n.setText(_translate("Kassenterminal", "N"))
        self.pushButton_m.setText(_translate("Kassenterminal", "M"))
        self.pushButton_j.setText(_translate("Kassenterminal", "J"))
        self.pushButton_s.setText(_translate("Kassenterminal", "S"))
        self.pushButton_o.setText(_translate("Kassenterminal", "O"))
        self.pushButton_q.setText(_translate("Kassenterminal", "Q"))
        self.pushButton_i.setText(_translate("Kassenterminal", "I"))
        self.pushButton_w.setText(_translate("Kassenterminal", "W"))
        self.pushButton_u.setText(_translate("Kassenterminal", "U"))
        self.pushButton_d.setText(_translate("Kassenterminal", "D"))
        self.pushButton_dot.setText(_translate("Kassenterminal", "."))
        self.pushButton_komma.setText(_translate("Kassenterminal", ","))
        self.pushButton_enter.setText(_translate("Kassenterminal", "↵"))
        self.pushButton_a_4.setText(_translate("Kassenterminal", "4"))
        self.pushButton_a_6.setText(_translate("Kassenterminal", "6"))
        self.pushButton_v.setText(_translate("Kassenterminal", "V"))
        self.pushButton_p.setText(_translate("Kassenterminal", "P"))
        self.pushButton_b.setText(_translate("Kassenterminal", "B"))
        self.pushButton_k.setText(_translate("Kassenterminal", "K"))
        self.pushButton_backspace_3.setText(_translate("Kassenterminal", "⌫"))
        self.pushButton_e.setText(_translate("Kassenterminal", "E"))
        self.pushButton_x.setText(_translate("Kassenterminal", "X"))
        self.pushButton_c.setText(_translate("Kassenterminal", "C"))
        self.pushButton_ae.setText(_translate("Kassenterminal", "Ä"))
        self.pushButton_a_1.setText(_translate("Kassenterminal", "1"))
        self.pushButton_a.setText(_translate("Kassenterminal", "A"))
        self.pushButton_t.setText(_translate("Kassenterminal", "T"))
        self.pushButton_z.setText(_translate("Kassenterminal", "Z"))
        self.pushButton_a_3.setText(_translate("Kassenterminal", "3"))
        self.pushButton_l.setText(_translate("Kassenterminal", "L"))
        self.pushButton_a_2.setText(_translate("Kassenterminal", "2"))
        self.pushButton_r.setText(_translate("Kassenterminal", "R"))
        self.pushButton_a_9.setText(_translate("Kassenterminal", "9"))
        self.pushButton_g.setText(_translate("Kassenterminal", "G"))
        self.pushButton_ue.setText(_translate("Kassenterminal", "Ü"))
        self.pushButton_f.setText(_translate("Kassenterminal", "F"))
        self.pushButton_oe.setText(_translate("Kassenterminal", "Ö"))
        self.pushButton_h.setText(_translate("Kassenterminal", "H"))
        self.pushButton_minus.setText(_translate("Kassenterminal", "-"))
        self.pushButton_y.setText(_translate("Kassenterminal", "Y"))
        self.pushButton_a_7.setText(_translate("Kassenterminal", "7"))
        self.pushButton_a_8.setText(_translate("Kassenterminal", "8"))
        self.pushButton_a_5.setText(_translate("Kassenterminal", "5"))
        self.pushButton_a_0.setText(_translate("Kassenterminal", "0"))
        self.pushButton_sz.setText(_translate("Kassenterminal", "ß"))
        self.menuDatei.setTitle(_translate("Kassenterminal", "Menü"))
        self.actionNeustart.setText(_translate("Kassenterminal", "Neustart"))
        self.actionServicemodus.setText(_translate("Kassenterminal", "Servicemodus"))
from ..CartTableView import CartTableView
from ..MyQLineEdit import MyQLineEdit
import icons_rc
